"""empty message

Revision ID: 09800a6f86cf
Revises: 80bbe92f754d
Create Date: 2021-04-21 10:32:45.996352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '09800a6f86cf'
down_revision = '80bbe92f754d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'supervisor', 'planner', 'worker', name='role_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'supervisor', 'planner', 'worker', name='role_enum'),
               nullable=False)
    # ### end Alembic commands ###
