"""empty message

Revision ID: 31c1b88053b8
Revises: fd464d366aa7
Create Date: 2021-04-16 11:00:51.232554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '31c1b88053b8'
down_revision = 'fd464d366aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.Enum('admin', 'supervisor', 'planner', 'worker', name='role_enum'), nullable=True))
    op.drop_column('user', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('level', postgresql.ENUM('admin', 'supervisor', 'planner', 'worker', name='role_enum'), autoincrement=False, nullable=True))
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
