"""empty message

Revision ID: 80bbe92f754d
Revises: 31c1b88053b8
Create Date: 2021-04-16 14:29:15.825778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80bbe92f754d'
down_revision = '31c1b88053b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'supervisor', 'planner', 'worker', name='role_enum'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'role',
               existing_type=postgresql.ENUM('admin', 'supervisor', 'planner', 'worker', name='role_enum'),
               nullable=True)
    # ### end Alembic commands ###
